# Generated by Django 5.1.1 on 2024-09-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cpagos', models.CharField(max_length=255)),
                ('cuota_inicial', models.FloatField()),
                ('cuota_mensual', models.FloatField()),
                ('fecha_inicio_pago', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('plazo_años', models.IntegerField()),
                ('TEA', models.FloatField()),
                ('descuento', models.FloatField()),
                ('dias_pago', models.CharField(max_length=255)),
                ('cuota_Balloon', models.FloatField()),
                ('cuota_Balloon_meses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_principal', models.BooleanField(default=False, null=True)),
                ('max_length', models.IntegerField(default=1, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('contrato', models.BinaryField(blank=True, null=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('tipo_empresa', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11)),
                ('pais', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('id_descri_empresa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaDatosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cpagos', models.IntegerField()),
                ('id_persona', models.IntegerField()),
                ('id_unidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.CharField(max_length=255)),
                ('conyuge', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('profesion', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('centro_trabajo', models.CharField(max_length=255)),
                ('direccion_laboral', models.CharField(max_length=255)),
                ('antiguedad_laboral', models.CharField(max_length=255)),
                ('separacion', models.CharField(max_length=255)),
                ('nombre_rol', models.IntegerField()),
                ('nombre_area', models.IntegerField()),
                ('nombre_origen', models.CharField(max_length=255)),
                ('nombre_canal', models.CharField(max_length=255)),
                ('nombre_medio', models.CharField(max_length=255)),
                ('nombre_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField()),
                ('deuda_total', models.FloatField()),
                ('amortizacion', models.FloatField()),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cronogramapagos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('contrato', models.BinaryField(blank=True, null=True)),
                ('field_1', models.CharField(max_length=255)),
                ('field_2', models.CharField(max_length=255)),
                ('field_3', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_observaciones', models.CharField(max_length=255)),
                ('adjuntar_informacion', models.CharField(max_length=255)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana_lote', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('perimetro', models.CharField(max_length=255)),
                ('colindancia_frente', models.CharField(max_length=255)),
                ('colindancia_derecha', models.CharField(max_length=255)),
                ('colindancia_izquierda', models.CharField(max_length=255)),
                ('colindancia_fondo', models.CharField(max_length=255)),
                ('distancia_frente', models.FloatField()),
                ('distancia_derecha', models.FloatField()),
                ('distancia_izquierda', models.FloatField()),
                ('distancia_fondo', models.FloatField()),
                ('precio_m2', models.FloatField()),
                ('estado', models.CharField(max_length=255)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.proyecto')),
            ],
        ),
    ]
