# Generated by Django 5.1.1 on 2024-10-07 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cpagos', models.CharField(max_length=255)),
                ('cuota_inicial', models.FloatField()),
                ('cuota_mensual', models.FloatField()),
                ('fecha_inicio_pago', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('plazo_años', models.IntegerField()),
                ('TEA', models.FloatField()),
                ('descuento', models.FloatField()),
                ('dias_pago', models.CharField(max_length=255)),
                ('cuota_Balloon', models.FloatField()),
                ('cuota_Balloon_meses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_principal', models.BooleanField(default=False, null=True)),
                ('max_length', models.IntegerField(default=1, null=True)),
                ('deleted', models.BooleanField(default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('contrato', models.BinaryField(blank=True, null=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('tipo_empresa', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11)),
                ('pais', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('id_descri_empresa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('ocupacion', models.CharField(max_length=255)),
                ('centro_trabajo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('num_documento', models.CharField(max_length=255)),
                ('conyuge', models.BooleanField()),
                ('telefono_fijo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField()),
                ('deuda_total', models.FloatField()),
                ('amortizacion', models.FloatField()),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cronogramapagos')),
            ],
        ),
        migrations.CreateModel(
            name='FichaDatosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_legal', models.CharField(max_length=255)),
                ('fecha_cierre', models.DateField(max_length=255)),
                ('fecha_separacion', models.DateField()),
                ('cod_boleta', models.CharField(max_length=100)),
                ('asesor', models.CharField(max_length=255)),
                ('id_cpagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cronogramapagos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('contrato', models.BinaryField(blank=True, null=True)),
                ('field_1', models.CharField(max_length=255)),
                ('field_2', models.CharField(max_length=255)),
                ('field_3', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_observaciones', models.CharField(max_length=255)),
                ('adjuntar_informacion', models.CharField(max_length=255)),
                ('id_persona_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.personaclient')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=255)),
                ('usuario', models.BooleanField(default=False)),
                ('canal', models.CharField(max_length=255)),
                ('medio', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('origen', models.CharField(max_length=255)),
                ('id_fichadc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.fichadatoscliente')),
                ('id_persona_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.personaclient')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=8)),
                ('conyuge', models.BooleanField(default=False)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=9)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('rol', models.CharField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('tipo_proyecto', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana_lote', models.IntegerField()),
                ('area', models.CharField(max_length=255)),
                ('perimetro', models.CharField(max_length=255)),
                ('colindancia_frente', models.CharField(max_length=255)),
                ('colindancia_derecha', models.CharField(max_length=255)),
                ('colindancia_izquierda', models.CharField(max_length=255)),
                ('colindancia_fondo', models.CharField(max_length=255)),
                ('distancia_frente', models.FloatField()),
                ('distancia_derecha', models.FloatField()),
                ('distancia_izquierda', models.FloatField()),
                ('distancia_fondo', models.FloatField()),
                ('precio_m2', models.FloatField()),
                ('estado', models.CharField(max_length=255)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='fichadatoscliente',
            name='id_lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.unidad'),
        ),
    ]
